"""posts table

Revision ID: 731daee12266
Revises: b2acbfc9682e
Create Date: 2020-04-29 19:56:50.830399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731daee12266'
down_revision = 'b2acbfc9682e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_comments', table_name='post')
    op.create_index(op.f('ix_post_comments'), 'post', ['comments'], unique=False)
    op.drop_index('ix_post_email', table_name='post')
    op.create_index(op.f('ix_post_email'), 'post', ['email'], unique=False)
    op.drop_index('ix_post_username', table_name='post')
    op.create_index(op.f('ix_post_username'), 'post', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_username'), table_name='post')
    op.create_index('ix_post_username', 'post', ['username'], unique=1)
    op.drop_index(op.f('ix_post_email'), table_name='post')
    op.create_index('ix_post_email', 'post', ['email'], unique=1)
    op.drop_index(op.f('ix_post_comments'), table_name='post')
    op.create_index('ix_post_comments', 'post', ['comments'], unique=1)
    # ### end Alembic commands ###
